#!/bin/bash
#SBATCH -N 16
#SBATCH -C knl,quad,cache
#SBATCH -p debug
#SBATCH -J mfix
#SBATCH --mail-user=asalmgren@lbl.gov
#SBATCH --mail-type=ALL
#SBATCH -t 00:20:00

#OpenMP settings:
export OMP_NUM_THREADS=1
export OMP_PLACES=threads
export OMP_PROC_BIND=spread

#run the application:
#cd /global/cscratch1/sd/almgren/BENCH03/Size001
#srun -n 1 -c 4 --cpu_bind=cores ../mfix inputs >& out.001

#cd /global/cscratch1/sd/almgren/BENCH03/Size004
#srun -n 4 -c 4 --cpu_bind=cores ../mfix inputs >& out.004

#cd /global/cscratch1/sd/almgren/BENCH03/Size016
#srun -n 16 -c 4 --cpu_bind=cores ../mfix inputs >& out.016

#cd /global/cscratch1/sd/almgren/BENCH03/Size064
#srun -n 64 -c 4 --cpu_bind=cores ../mfix inputs >& out.064.new

#cd /global/cscratch1/sd/almgren/BENCH03/Size256
#srun -n 256 -c 4 --cpu_bind=cores ../mfix inputs >& out.256.right

cd /global/cscratch1/sd/almgren/BENCH03/Size1024
srun -n 1024 -c 4 --cpu_bind=cores ../mfix inputs >& out.1024
