# AMREX_HOME defines the directory in which we will find all the AMReX code
AMREX_HOME ?= ../subprojects/amrex
AMREX_HYDRO_HOME ?= ../subprojects/AMReX-Hydro

# TOP defines the directory in which we will find Source, Exec, etc
TOP = ..

# compilation options
COMP    = gnu
USE_MPI = TRUE
USE_OMP = FALSE
USE_CSG = FALSE

USE_CUDA   = FALSE
USE_HIP    = FALSE
USE_DPCPP  = FALSE
USE_CCACHE = TRUE

USE_HYPRE = FALSE

DEBUG     = TRUE
DEBUG     = FALSE

PROFILE       = FALSE
TRACE_PROFILE = FALSE
COMM_PROFILE  = FALSE
TINY_PROFILE  = FALSE

# physics
DIM      = 3

include ./Make.mfix
