# AMREX_HOME defines the directory in which we will find all the AMReX code
AMREX_HOME ?= ../../amrex

# TOP defines the directory in which we will find Source, Exec, etc
TOP = ..

# compilation options
COMP    = gnu
USE_MPI = TRUE
USE_OMP = FALSE

DEBUG     = TRUE
TEST      = TRUE

USE_ASSERTION = 1


PROFILE       = TRUE
TRACE_PROFILE = FALSE
COMM_PROFILE  = FALSE
TINY_PROFILE  = FALSE

# physics
DIM      = 3

include ./Make.mfix
