AMREX_HOME ?= ../../subprojects/amrex
TOP = .

EBASE := post-mfix

BL_NO_FORT = TRUE

DEBUG    = TRUE
DEBUG    = FALSE

DIM = 3

COMP = gcc

PRECISION = DOUBLE

USE_MPI  = FALSE
USE_OMP  = FALSE
USE_CUDA = FALSE

include ./post-mfix/Make.post_mfix
