PRECISION = DOUBLE

DEBUG	= TRUE
DEBUG	= FALSE

DIM	= 3

COMP =gcc

USE_MPI=FALSE
USE_OMP=FALSE

EBASE = mfix

INCLUDE_LOCATIONS += .
VPATH_LOCATIONS   += .
vpathdir          += .

include ../Make.mfix
