AMREX_HOME = ../../subprojects/amrex
AMREX_HYDRO_HOME = ../../subprojects/AMReX-Hydro

TOP = .

EBASE := FilterML

BL_NO_FORT = TRUE

DEBUG    = TRUE
DEBUG    = FALSE

DIM = 3

COMP = gcc

USE_PARTICLES = TRUE

PRECISION = DOUBLE

USE_MPI  = TRUE
USE_OMP  = FALSE
USE_CUDA = FALSE

USE_HDF5  = FALSE
USE_HDF5_ZFP = FALSE

include ./FilterML/Make.FilterML
